create table MOVIE (
   movie_id bigint not null,
    title varchar(255),
    primary key (movie_id)
);

create table USERS (
   id integer generated by default as identity,
    user_id integer,
    movie_id bigint,
    primary key (id)
);

alter table USERS
   add constraint FKg1r6c3k5igqtsxyehfqfnfalm
   foreign key (movie_id)
   references MOVIE;