drop table if exists movie cascade;
drop table if exists users cascade;
create table movie (
    id integer,
    title varchar(255),
    primary key (id)
);
create table users (
    movie_id integer,
    user_id integer,
    id bigint generated by default as identity,
    primary key (id)
);